name: Generate Snake

on:
  schedule:
    # Run every 5 minutes
    - cron: "*/1 * * * *"

  # Run on workflow_dispatch and every push on the main branch
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
    
      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/GitHub-contribution-grid-snake.svg
            dist/GitHub-contribution-grid-snake-dark.svg?palette=dark
            dist/GitHub-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Edit dark mode SVG
        run: |
          sed -i 's/fill: #1c1e26/fill: #bfd6f6/g' dist/GitHub-contribution-grid-snake-dark.svg
          sed -i 's/fill: #2f333a/fill: #8dbdff/g' dist/GitHub-contribution-grid-snake-dark.svg
          sed -i 's/fill: #586069/fill: #64a1f4/g' dist/GitHub-contribution-grid-snake-dark.svg
          sed -i 's/fill: #6a737d/fill: #4b91f1/g' dist/GitHub-contribution-grid-snake-dark.svg
          sed -i 's/fill: #959da5/fill: #3c7dd9/g' dist/GitHub-contribution-grid-snake-dark.svg

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
